import Head from 'next/head'
import Script from 'next/script'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Landing from '../components/Landing'
import About from '../components/About'
import Clients from '../components/Clients'
import Services from '../components/Services'
import Action from '../components/Action'
import Testimonials from '../components/Testimonials'
import Team from '../components/Team'
import Contact from '../components/Contact'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bussiness Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
        <link rel="icon" href="/favicon.ico" />
        
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></Script>
      </Head>
      <Header/>
      <Landing/>
      <About/>
      <Clients/>
      <Services/>
      <Action/>
      <Testimonials/>
      <Team/>
      <Contact/>
      <Footer/>
      
      
    </div>
  )
}
